### ISSUE TITLE
libiscsi version for libiscsi-python?

### ISSUE THREAD

**Issue by rosjat** [sahlberg/libiscsi-python#1]
Hey ronnie,

what version of libiscsi should I use to run this package? I used the current master of libiscsi  but I got a traceback as I tried to import libiscsi in python 

Traceback (most recent call last):
  File" <stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/libiscsi-1.0.post1-py2.7-linux-x86_64.egg/libiscsi/**init**.py", line 17, in <module>
    from libiscsi import *
  File "/usr/local/lib/python2.7/dist-packages/libiscsi-1.0.post1-py2.7-linux-x86_64.egg/libiscsi/libiscsi.py", line 29, in <module>
    _libiscsi = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/libiscsi-1.0.post1-py2.7-linux-x86_64.egg/libiscsi/libiscsi.py", line 25, in swig_import_helper
    _mod = imp.load_module('_libiscsi', fp, pathname, description)
ImportError: libiscsi.so.4: cannot open shared object file: No such file or directory

regards

Markus

**Comment by rosjat** [comment]
this might not be a problem of the libiscsi library  since I could both build and install. I did build and installed libiscsi as root may this be the problem since the doc states building of libisci as non root but install as root?

**Comment by rosjat** [comment]
okay seems to be sorted out, some stuff wasn't up to date on my system
